### PR TITLE
[1.2.0] Public Log Interface [API-872] 

### LINKED ISSUE #625: Can't use own logger with a new client version
Go version: 1.17
Hazelcast Go Client version: 1.0.0
Hazelcast server version: 4.x
Number of the clients:
Cluster size, i.e. the number of Hazelcast cluster members:
OS version : Linux

#### Expected behaviour
logger.Config has method SetLogger that allows to set a custom logger matching Logger interface

#### Actual behaviour
logger.Config struct has no way to specify a custom logger implementation. Also there is no way to redirect log output to a file for example.

#### Steps to reproduce the behaviour

### PR DESCRIPTION
**Pull request by utku-caglayan**
Fixes #625 

Left PR: https://github.com/hazelcast/hazelcast-go-client/pull/665
as is on purpose, so that I thought we can compare and discuss the changes between them.

/internal/logger => logger.Logger interface can be removed by using concrete type "LogAdaptor" all over the codebase. But I think it leads to bad couplings. I would love to hear your thoughts.

Also I thought DefaultLogger type can be exported to user, as guidance or custom use. However I am not sure if this is right way, so did not go through with it yet

### CODE REVIEW

**Comment by yuce** [comment]
> Also I thought DefaultLogger type can be exported to user, as guidance or custom use. However I am not sure if this is right way, so did not go through with it yet

That's an internal implementation detail, let's not make it public.

> /internal/logger => logger.Logger interface can be removed by using concrete type "LogAdaptor" all over the codebase. But I think it leads to bad couplings.

I am not sure about how it leads to bad coupling but without that we have to change quite a bit of logging related code, and also the logging code becomes much more verbose.

File: internal/cluster/failover_service.go [hunk 1]
```diff
@@ -39,9 +39,9 @@ type CandidateCluster struct {
 	ClusterName        string
 }
 
-type addrFun func(*pubcluster.Config, ilogger.Logger) (AddressProvider, AddressTranslator)
+type addrFun func(*pubcluster.Config, logger.Logger) (AddressProvider, AddressTranslator)
```
Comment (yuce) [inline internal/cluster/failover_service.go:42]: Wer can name import aliases for public packages with `pub` prefix, like `publogger`.

**Review by yuce — CHANGES_REQUESTED** [review]

File: internal/cluster/failover_service.go (hunk 1 above)
Comment (utku-caglayan) [reply internal/cluster/failover_service.go:42]: This is internal logger package. I could not understand the point. Can you explain further?

File: internal/cluster/connection_manager.go [hunk 2]
```diff
@@ -26,15 +26,16 @@ import (
 	"sync/atomic"
 	"time"
 
+	"github.com/hazelcast/hazelcast-go-client/internal/lifecycle"
+	"github.com/hazelcast/hazelcast-go-client/internal/logger"
+
```
[the remark this answers is not in the document]
Comment (utku-caglayan) [reply internal/cluster/connection_manager.go]: Oh thanks

File: internal/cloud/cloud_discovery.go [hunk 3]
```diff
@@ -24,19 +24,19 @@ import (
...
 
 type DiscoveryClient struct {
-	logger     logger.Logger
+	logger     logger2.Logger
 	httpClient *rest.HTTPClient
 	token      string
 }
 
-func NewDiscoveryClient(config *cluster.CloudConfig, logger logger.Logger) *DiscoveryClient {
+func NewDiscoveryClient(config *cluster.CloudConfig, logger logger2.Logger) *DiscoveryClient {
```
[the remark this answers is not in the document]
Comment (utku-caglayan) [reply internal/cloud/cloud_discovery.go]: Yes, similar cases were present on other files too. Fixed that, thanks

File: internal/cluster/failover_service.go (hunk 1 above)
Comment (yuce) [reply internal/cluster/failover_service.go:42]: I don't think we need the internal `logger.Logger` anymore, do we?

**Comment by yuce** [comment]
@utku-caglayan Could you add package level documentation to the public `logger` package in `doc,go`? It would also be nice to add `example.go` with an example about how to override the default logger.

File: internal/logger/default_logger.go [hunk 4]
```diff
@@ -21,124 +21,122 @@ import (
...
-	if l.canLogInfo() {
-		callerName := l.findCallerFuncName()
-		s := callerName + "\n" + infoPrefix + ": " + fmt.Sprint(args...)
-		l.Output(logCallDepth, s)
+	loggerLevel, err := logger.GetLogLevel(l.Level)
+	if err != nil {
+		fmt.Println("logger has invalid logger level, will not logger something useful")
+		return false
 	}
+	return loggerLevel >= numericLevel
```
Comment (yuce) [inline internal/logger/default_logger.go:75]: The variable names are not very clear. How about `currentLevel >= wantedLevel`?

File: internal/logger/default_logger.go [hunk 5]
```diff
@@ -21,124 +21,122 @@ import (
...
 }
 
-func (l *DefaultLogger) Infof(format string, values ...interface{}) {
-	if l.canLogInfo() {
-		s := fmt.Sprintf("INFO : %s", fmt.Sprintf(format, values...))
-		l.Output(logCallDepth, s)
+func (l *DefaultLogger) Log(level logger.Level, formatter func() string) {
+	if !l.canLog(level) || formatter == nil {
```
Comment (yuce) [inline internal/logger/default_logger.go:79]: No need to check for `format == nil`. In that case the code will panic, and that's OK.

File: internal/logger/default_logger.go [hunk 6]
```diff
@@ -21,124 +21,122 @@ import (
...
+		return
 	}
+	s := fmt.Sprintf("%s: %s", strings.ToUpper(level.String()), formatter())
+	_ = l.Output(logCallDepth, s)
```
Comment (yuce) [inline internal/logger/default_logger.go:83]: How about a comment explaining why the error was ignored?

File: internal/logger/default_logger.go (hunk 5 above)
Comment (yuce) [reply internal/logger/default_logger.go:79]: How about moving `canLog` here in order to get rid of one function call?

File: internal/logger/default_logger.go [hunk 7]
```diff
@@ -21,124 +21,122 @@ import (
...
 
-func (l *DefaultLogger) Infof(format string, values ...interface{}) {
-	if l.canLogInfo() {
-		s := fmt.Sprintf("INFO : %s", fmt.Sprintf(format, values...))
-		l.Output(logCallDepth, s)
+func (l *DefaultLogger) Log(level logger.Level, formatter func() string) {
+	if !l.canLog(level) || formatter == nil {
+		return
 	}
+	s := fmt.Sprintf("%s: %s", strings.ToUpper(level.String()), formatter())
```
Comment (yuce) [inline internal/logger/default_logger.go:82]: Note that, in the old default logger the level was padded to 5 chars, so it displayed like:
```
2021/11/09 11:19:52 TRACE: event.DispatchService.Publish: internal.cluster.connection
2021/11/09 11:19:52 INFO : connected to cluster: integration-test
```
Currently it displays:
```
2021/11/09 11:19:52 TRACE: event.DispatchService.Publish: internal.cluster.connection
2021/11/09 11:19:52 INFO: connected to cluster: integration-test
```

File: internal/logger/default_logger.go [hunk 8]
```diff
@@ -21,124 +21,122 @@ import (
...
+func (la LogAdaptor) Trace(f func() string) {
+	la.Log(logger.TraceLevel, f)
 }
 
-func (l *DefaultLogger) findCallerFuncName() string {
-	pc, _, _, _ := runtime.Caller(logCallDepth)
-	return runtime.FuncForPC(pc).Name()
+// Info runs the given function to generate the logger string, if logger level is info or finer.
+func (la LogAdaptor) Info(f func() string) {
+	la.Log(logger.InfoLevel, f)
```
Comment (yuce) [inline internal/logger/default_logger.go:108]: This `Info` function does something different than the old one. If it's not being used, let's remove it.

File: internal/logger/default_logger.go [hunk 9]
```diff
@@ -21,124 +21,122 @@ import (
...
+	la.Log(logger.InfoLevel, func() string {
+		return fmt.Sprintf(format, values...)
+	})
 }
 
-func (l *DefaultLogger) canLogInfo() bool {
-	return l.Level >= infoLevel
+// Warn formats the given string with the given values, if logger level is warn or finer.
+func (la LogAdaptor) Warn(f func() string) {
+	la.Log(logger.WarnLevel, f)
```
Comment (yuce) [inline internal/logger/default_logger.go:120]: This `Warn` function does something different than the old one. If it's not being used, let's remove it.

File: internal/logger/default_logger.go [hunk 10]
```diff
@@ -21,124 +21,122 @@ import (
...
+		return err.Error()
+	})
 }
 
-func (l *DefaultLogger) CanLogDebug() bool {
-	return l.Level >= debugLevel
+// Errorf formats the given string with the given values, if logger level is error or finer.
+func (la LogAdaptor) Errorf(format string, values ...interface{}) {
+	la.Log(logger.ErrorLevel, func() string {
+		return fmt.Sprintf(format, values...)
```
Comment (yuce) [inline internal/logger/default_logger.go]: This `Error` method is different from the old one, which created an error with the given format and values.

File: logger/logger.go [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+	_, found := nameToLevel[Level(logLevelStr)]
+	return found
+}
+
+// GetLogLevel returns the corresponding logger level with the given string if it exists, otherwise returns an error.
+func GetLogLevel(logLevel Level) (int, error) {
+	if !isValidLogLevel(logLevel) {
+		return 0, hzerrors.NewIllegalArgumentError(fmt.Sprintf("no logger level found for %s", logLevel), nil)
+	}
+	return nameToLevel[logLevel], nil
```
Comment (yuce) [inline logger/logger.go:50]: Do we need to check `nameToLevel` twice? I think we could get rid of `isValidLogLevel` too.

File: logger/logger_config.go [hunk 12]
```diff
@@ -25,6 +25,8 @@ type Level string
 const (
 	// OffLevel disables logging.
 	OffLevel Level = "off"
+	// CriticalLevel level. Used for errors that should definitely be noted.
```
Comment (yuce) [inline logger/logger_config.go:28]: Maybe we can rewrite these doc lines like:
```
CriticalLevel is used for errors that halts the client.
```

File: logger/logger_config.go [hunk 13]
```diff
@@ -44,11 +46,16 @@ func (l Level) String() string {
 }
 
 type Config struct {
-	Level Level `json:",omitempty"`
+	Level  Level  `json:",omitempty"`
+	Custom Logger `json:"-"`
+}
+
+func (c *Config) SetLogger(customLogger Logger) {
+	c.Custom = customLogger
```
Comment (yuce) [inline logger/logger_config.go:54]: I think we don't need this method, since it doesn't make setting the logger easier.

File: logger/logger.go (hunk 11 above)
Comment (yuce) [reply logger/logger.go:50]: I think we can convert `nameToLevel` to a switch statement.

File: proxy.go [hunk 14]
```diff
@@ -394,7 +394,7 @@ func (p *proxy) makeEntryNotifiedListenerHandler(handler EntryNotifiedHandler) e
 		affectedEntries int32) {
 		key, value, oldValue, mergingValue, err := p.decodeEntryNotified(binKey, binValue, binOldValue, binMergingValue)
 		if err != nil {
-			p.logger.Errorf("error at AddEntryListener: %w", err)
+			p.logger.Errorf("error at AddEntryListener: %s", err)
```
Comment (yuce) [inline proxy.go]: Let's keep `%w`

**Review by yuce — APPROVED** [review]

**Review by yuce — CHANGES_REQUESTED** [review]
Thanks for the PR. A few comments to make it even better.

File: client.go [hunk 15]
```diff
@@ -217,6 +225,11 @@ func (c *Client) GetDistributedObjectsInfo(ctx context.Context) ([]types.Distrib
 	return codec.DecodeClientGetDistributedObjectsResponse(resp), nil
 }
 
+// SetLogger sets a logger implementing logger.LogAdaptor
+func (c *Client) SetLogger(logger logger.Logger) {
```
[the remark this answers is not in the document]
Comment (utku-caglayan) [reply client.go]: Thanks for catching that, removed as you suggested

File: client.go [hunk 16]
```diff
@@ -107,32 +108,39 @@ func newClient(config Config) (*Client, error) {
...
 	if err != nil {
 		return nil, err
 	}
-	clientLogger := ilogger.NewWithLevel(logLevel)
 	serializationService, err := serialization.NewService(&config.Serialization)
 	if err != nil {
 		return nil, err
 	}
-	clientLogger.Trace(func() string { return fmt.Sprintf("creating new client: %s", name) })
+	clientLogger.Log(logger.TraceLevel, func() string { return fmt.Sprintf("creating new client: %s", name) })
```
[the remark this answers is not in the document]
Comment (utku-caglayan) [reply client.go]: Ty, fixed as suggested

File: client.go [hunk 17]
```diff
@@ -107,32 +108,39 @@ func newClient(config Config) (*Client, error) {
...
 	c.createComponents(&config)
 	return c, nil
 }
 
+func loggerFromConf(config Config) (logger.Logger, error) {
+	if config.Logger.Custom != nil {
+		return config.Logger.Custom, nil
+	}
+	clientLogger := ilogger.NewWithLevel(config.Logger.Level)
+	return clientLogger, nil
```
[the remark this answers is not in the document]
Comment (utku-caglayan) [reply client.go]: Thanks, fixed it.

File: logger/logger_config.go (hunk 13 above)
Comment (utku-caglayan) [reply logger/logger_config.go]: Agree, removed it as you suggested

File: internal/logger/default_logger.go (hunk 4 above)
Comment (utku-caglayan) [reply internal/logger/default_logger.go:75]: Changed this part, please take a look again

File: internal/logger/default_logger.go (hunk 6 above)
Comment (utku-caglayan) [reply internal/logger/default_logger.go]: Sure, just thought it is common practice to ignore logging error. Added a comment as suggested

File: internal/logger/default_logger.go [hunk 18]
```diff
@@ -44,43 +44,39 @@ const (
...
 
 // New returns a Default Logger with defaultLogLevel.
 func New() *DefaultLogger {
+	numericLevel, _ := logger.GetLogLevel(defaultLogLevel) // defaultLogLevel exists, no err
 	return &DefaultLogger{
 		Logger: log.New(os.Stderr, "", log.LstdFlags),
-		Level:  defaultLogLevel,
+		Level:  numericLevel,
 	}
 }
```
Comment (yuce) [inline internal/logger/default_logger.go:57]: This function can just call `NewWithLevel` with the default log level:
```
return NewWithLevel(defaultLogLevel)
```

File: internal/logger/default_logger.go [hunk 19]
```diff
@@ -44,43 +44,39 @@ const (
...
 		Logger: log.New(os.Stderr, "", log.LstdFlags),
-		Level:  loggingLevel,
-	}
+		Level:  numericLevel,
+	}, nil
 }
 
-func (l *DefaultLogger) canLog(level logger.Level) bool {
+func (l *DefaultLogger) Log(level logger.Level, formatter func() string) {
 	numericLevel, err := logger.GetLogLevel(level)
```
Comment (yuce) [inline internal/logger/default_logger.go:71]: Let's rename `numericLevel` to something better. How about `wantedLevel`?

File: logger/logger_config.go [hunk 20]
```diff
@@ -25,7 +25,7 @@ type Level string
 const (
 	// OffLevel disables logging.
 	OffLevel Level = "off"
-	// CriticalLevel level. Used for errors that should definitely be noted.
+	// CriticalLevel is used for errors that halts the client.
 	CriticalLevel Level = "critical"
 	// ErrorLevel level. Logs. Used for errors that should definitely be noted.
```
Comment (yuce) [inline logger/logger_config.go:30]: Can you use the same document format for other log level doc comments? `ErrorLevel is used ...`, etc.

File: logger/logger.go [hunk 21]
```diff
@@ -23,29 +22,24 @@ const (
...
+	case ErrorLevel:
+		return errorLevel, nil
+	case WarnLevel:
+		return warnLevel, nil
+	case InfoLevel:
+		return infoLevel, nil
+	case DebugLevel:
+		return debugLevel, nil
+	case TraceLevel:
+		return traceLevel, nil
```
Comment (yuce) [inline logger/logger.go:41]: Does it make sense to invert the order the levels to pay the least cost the common scenario, such as: Trace, Debug, Info, Warn, Error, Critical, Off? (so getting the Trace level is fastest, while getting the Off level is the slowest, which is not used much).

**Review by yuce — CHANGES_REQUESTED** [review]

File: internal/cluster/failover_service.go (hunk 1 above)
Comment (utku-caglayan) [reply internal/cluster/failover_service.go]: removed as discussed

File: internal/logger/default_logger.go (hunk 18 above)
Comment (utku-caglayan) [reply internal/logger/default_logger.go:57]: Thanks, will fix that

File: client.go [hunk 22]
```diff
@@ -107,24 +107,23 @@ func newClient(config Config) (*Client, error) {
...
 		name = fmt.Sprintf("hz.client_%d", id)
 	}
-	logLevel, err := ilogger.GetLogLevel(config.Logger.Level)
+	serializationService, err := serialization.NewService(&config.Serialization)
 	if err != nil {
 		return nil, err
 	}
-	clientLogger := ilogger.NewWithLevel(logLevel)
-	serializationService, err := serialization.NewService(&config.Serialization)
+	clientLogger, err := loggerFromConf(config)
```
Comment (yuce) [inline client.go:114]: Is there a reason why you've changed the creation order of serialization service and logger?

File: logger/logger.go (hunk 21 above)
Comment (utku-caglayan) [reply logger/logger.go:41]: https://play.golang.org/p/LcdE381wsK9
I could not find a meaningful difference. Do you think we can prove this? I would love to learn more about this.
usage: go test --benchmark=. benchmark_test.go

source: https://adayinthelifeof.nl/2021/03/04/go-map-vs-switch.html

If we do not see a performance improvement with the suggested ordering approach, I think it would be more readable as is right now. Wdyt?

File: client.go (hunk 22 above)
Comment (utku-caglayan) [reply client.go:114]: I wanted logger to be closer to its first usage `clientLogger.Trace(func() string { return fmt.Sprintf("creating new client: %s", name) })`

File: logger/logger.go (hunk 21 above)
Comment (yuce) [reply logger/logger.go:41]: In the link you've sent it mentions that the switch cases are hold in a linked list, so the cases at the head of the list should be traversed first, hence should be faster to execute (although just a tiny bit). Not sure about the readability. Does ordering the cases in reverse make th switch less readable?

Comment (utku-caglayan) [reply logger/logger.go:41]: Ah okay, I did not read that part.
`go test --bench=. bench_test.go 
goos: darwin
goarch: arm64
BenchmarkForFrequentLogLevels-8                         309533968                3.617 ns/op
BenchmarkForFrequentLogLevelsWithOrderedSwitch-8        330991947                3.628 ns/op
`
Seeing the benchmark results, I assumed it was a jump table. Now I re-run benchmark few times, and it seems this result was a fluke. You are right, I do observe ordered one to be the faster variant. Will fix that, thanks!

File: internal/logger/default_logger.go (hunk 19 above)
Comment (utku-caglayan) [reply internal/logger/default_logger.go:71]: Sure 👍

File: logger/logger.go (hunk 11 above)
Comment (utku-caglayan) [reply logger/logger.go]: Great idea!

File: internal/logger/default_logger.go [hunk 23]
```diff
@@ -21,124 +21,114 @@ import (
...
+		Weight: numericLevel,
+	}, nil
 }
 
-func (l *DefaultLogger) Infof(format string, values ...interface{}) {
-	if l.canLogInfo() {
-		s := fmt.Sprintf("INFO : %s", fmt.Sprintf(format, values...))
-		l.Output(logCallDepth, s)
+func (l *DefaultLogger) Log(wantedLevel logger.Weight, formatter func() string) {
+	if l.Weight < wantedLevel {
```
Comment (sancar) [inline internal/logger/default_logger.go:68]: Isn't this line is wrong ? 
Lets say that we called 
```
// Infof formats the given string with the given values, if logger level is info or finer.
func (la LogAdaptor) Infof(format string, values ...interface{}) {
	la.Log(logger.WeightInfo, func() string {
		return fmt.Sprintf(format, values...)
	})
}
```
WeightInfo is 400. 
And lets say that the user configured to see the everything which means he set WeightTrace which means 
l.weight is Trace which is 600.

This means that we will not log in this case. But it should have been logged. Right ?

File: logger/logger.go [hunk 24]
```diff
@@ -0,0 +1,47 @@
+package logger
+
+import (
+	"fmt"
+
+	"github.com/hazelcast/hazelcast-go-client/internal/hzerrors"
+)
+
+// Logger is the interface that is used by client for logging.
+// Level is: type Level string
```
Comment (sancar) [inline logger/logger.go:10]: This documentation seems like out-of-date. 
We should describe what Weight is instead here I guess

**Review by sancar — APPROVED** [review]

File: logger/logger.go (hunk 24 above)
Comment (utku-caglayan) [reply logger/logger.go]: Thanks, great catch.

**Review by yuce — APPROVED** [review]
Thanks, looks good!
