### PR TITLE
Fixed ConnectionManager member removed handler [API-693]

### LINKED ISSUE #600: Client tries to connect non-existent members
Hazelcast Go Client version: 1.0.0
Cluster size, i.e. the number of Hazelcast cluster members: 2+

#### Expected behaviour

When a connection to a member is lost, use only the addresses from member list for reconnection attempts, not the cached addresses of connection manager.

#### Actual behaviour

When the member address doesn't exist anymore, getting the following log, although it's not possible to fix that connection:
```
INFO : found a broken connection to: 10.1.202.216:5701, trying to fix it
```

#### Steps to reproduce the behaviour

Follow https://github.com/hazelcast-guides/kubernetes/blob/master/doc/modules/ROOT/pages/index.adoc to create a Hazelcast cluster on Kubernetes and run the Go client code. Then, stop one of the members and check client logs:
```
kubectl delete pod hz-hazelcast-0
kubectl logs hazelcast-client
```

### PR DESCRIPTION
**Pull request by yuce**
* Fixes #600
* Send member list view request is sent to all members, not just the first seed.
* Various connection manager fixes

Tested with:
* https://github.com/SeriyBg/hazelcast-enterprise-operator/tree/hazelcast-status
* https://github.com/hazelcast-guides/kubernetes

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -39,6 +40,10 @@ import (
 	"github.com/hazelcast/hazelcast-go-client/types"
 )
 
+const (
+	ClientVersion = internal.ClientVersion
```
Comment (sancar) [inline client.go:44]: ide says unused? Is this a leftover?

Comment (yuce) [reply client.go:44]: No, it's not a leftover. I'll add a fake test so it doesn't cause any linter warnings.

File: internal/cluster/connection_manager.go [hunk 2]
```diff
@@ -60,6 +60,10 @@ const (
 	serializationVersion = 1
 )
 
+const (
+	clusterConnectionFixTimeout = 10 * time.Second
```
Comment (sancar) [inline internal/cluster/connection_manager.go:64]: what is this needed for ?  We already have connection timeout in NetworkConfig and also heartbeat timeout for this area? Why do we need another timeout ?

File: internal/cluster/connection_manager.go [hunk 3]
```diff
@@ -324,30 +328,39 @@ func (m *ConnectionManager) handleInitialMembersAdded(e event.Event) {
...
 		return
 	}
 	if e, ok := event.(*MembersAdded); ok {
+		m.logger.Trace(func() string {
+			return fmt.Sprintf("connectionManager.handleMembersAdded: %v", e.Members)
+		})
 		missingAddrs := m.connMap.FindAddedAddrs(e.Members, m.clusterService)
 		for _, addr := range missingAddrs {
-			if _, err := m.ensureConnection(context.TODO(), addr); err != nil {
+			if _, err := connectMember(context.TODO(), m, addr); err != nil {
```
Comment (sancar) [inline internal/cluster/connection_manager.go:341]: As far as I understand this also registers a membership listener to the connected member. 
We should not listen from all members. Single member delivers them already. In the case of split brain scenerious, we should follow single members view. 
Same goes for here. 
https://github.com/hazelcast/hazelcast-go-client/pull/617/files#diff-8235afecd77026dd0bddf3a2cd47ca4843345b3ddec987b0a5d45c127d14fadcR686

**Comment by sancar** [comment]
@yuce The issue seems testable to me. Can we write a unittest for this ?

File: internal/cluster/connection_manager.go (hunk 2 above)
Comment (yuce) [reply internal/cluster/connection_manager.go:64]: That limits the connection time for the context created in `checkFixConnection`.That's to prevent a very slow connection to

File: client_it_test.go [hunk 4]
```diff
@@ -553,3 +558,61 @@ func TestClientFailover_EECluster_Reconnection(t *testing.T) {
...
+	if !ok {
+		log.Fatalf("could not terminate member: %s", err.Error())
+	}
+	m, err := cls.RC.StartMember(ctx, cls.ClusterID)
+	if err != nil {
+		log.Fatal(err)
+	}
+	highlight(t, "Started member: %s", m.UUID)
+	time.Sleep(30 * time.Second)
+	assert.Equal(t, int64(memberCount+1), atomic.LoadInt64(&addedCount))
```
Comment (sancar) [inline client_it_test.go:612]: Can we implement something like assertTrueEventually that we have on the java to avoid sleep statements in the tests. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java#L1251

Comment (yuce) [reply client_it_test.go:612]: We can something like timed waitgroups. I've created a ticket for that: https://github.com/hazelcast/hazelcast-go-client/issues/621

File: internal/cluster/connection_manager.go (hunk 2 above)
Comment (yuce) [reply internal/cluster/connection_manager.go]: Removed that bit.

File: internal/cluster/connection_manager.go (hunk 3 above)
Comment (yuce) [reply internal/cluster/connection_manager.go:334]: Fixed.

**Review by sancar — APPROVED** [review]
